// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Technology } from '../../../technology/content-types/technology/technology';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Technology_Plain } from '../../../technology/content-types/technology/technology';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Project {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Name?: string;
    Description?: string;
    Media?: { data: Media[] };
    technologies?: { data: Technology[] };
    slug?: string;
  };
}
export interface Project_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Name?: string;
  Description?: string;
  Media?: Media_Plain[];
  technologies?: Technology_Plain[];
  slug?: string;
}

export interface Project_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Name?: string;
  Description?: string;
  Media?: number[];
  technologies?: number[];
  slug?: string;
}

export interface Project_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Name?: string;
  Description?: string;
  Media?: AdminPanelRelationPropertyModification<Media_Plain>[];
  technologies?: AdminPanelRelationPropertyModification<Technology_Plain>;
  slug?: string;
}
