// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface HeroComponent {
  heading: string;
  subheading?: string;
  description?: any;
  img?: { data: Media };
}
export interface HeroComponent_Plain {
  heading: string;
  subheading?: string;
  description?: any;
  img?: Media_Plain;
}

export interface HeroComponent_NoRelations {
  heading: string;
  subheading?: string;
  description?: any;
  img?: number;
}

