// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Hero {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    heading: string;
    subheading?: string;
    description?: any;
    img?: { data: Media };
  };
}
export interface Hero_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  heading: string;
  subheading?: string;
  description?: any;
  img?: Media_Plain;
}

export interface Hero_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  heading: string;
  subheading?: string;
  description?: any;
  img?: number;
}

export interface Hero_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  heading: string;
  subheading?: string;
  description?: any;
  img?: AdminPanelRelationPropertyModification<Media_Plain>;
}
